CREATE TABLE users
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	avatar TEXT,
	create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE scores
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	opponent_id INTEGER NOT NULL,
	score_user INTEGER NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id),
	FOREIGN KEY(opponent_id) REFERENCES users(id)
);